# Generated by Django 4.2.5 on 2023-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Masal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Masal adi")),
                ("description", models.TextField(verbose_name="Masal aciklamasi")),
                ("content", models.TextField(verbose_name="Masal icerigi")),
                (
                    "image",
                    models.CharField(max_length=50, verbose_name="Fotografinin ismi"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklendigi tarih"
                    ),
                ),
                (
                    "isPublished",
                    models.BooleanField(default=True, verbose_name="Yayinda"),
                ),
            ],
        ),
    ]
